angular.module('orderCloud', [
        'ngAnimate',
        'ngCookies',
        'ngMessages',
        'ngResource',
        'ngSanitize',
        'LocalForageModule',
        'ngTouch',
        'ui.tree',
        'ui.router',
        'ui.select',
        'ui.bootstrap',
        'toastr',
        'angular-busy',
        'jcs-autoValidate',
        'treeControl',
        'hl.sticky',
        'angularPayments',
        'ordercloud-angular-sdk'
    ]
);